baseURL = "http://codebynight.dev/"
languageCode = "en-us"
title = "Code by Night Learning to Program Journey Log"
theme = "PaperMod"
sectionPagesMenu = "main"

[params]
  env = "production"
  author = "Shivam Chhuneja"
  defaultTheme = "auto"
  googleAnalytics = "G-G64RCPRHRE"
  images = ["/images/preview.png"]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  description = "Code by Night is a programming learning journal - building and learning development in public."

  [params.label]
    icon = "images/logo.png"
    iconHeight = 50
    text = " "

  [params.homeInfoParams]
    Title = "A 30+ Guy Learning to Code in Public | Code by Night Dev Journey"
    Content = "Started learning Development late in life? So did I. Code by Night shares stories, projects, and behind-the-scenes thoughts from someone who’s walking the Developer path — building in public, reflecting in Markdown, and figuring things out."
      [[params.socialIcons]]
    name = "github"
    url = "https://github.com/shivamchhuneja"
    [[params.socialIcons]]
    name = "instagram"
    url = "https://instagram.com/shivamchhuneja"
    [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/shivamchhuneja"

[params.assets]
  favicon = "/images/favicon.ico"
  favicon16x16 = "/images/favicon-96x96.png"
  favicon32x32 = "/images/favicon-96x96.png"
  apple_touch_icon = "/images/apple-touch-icon.png"
  safari_pinned_tab = "/images/favicon.svg"

[params.social]
  github = "https://github.com/shivamchhuneja"
  instagram = "https://instagram.com/shivamchhuneja"
  linkedin = "https://www.linkedin.com/in/shivamchhuneja"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "upcoming"
    name = "Upcoming"
    url = "/upcoming/"
    weight = 3

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]
